services:
  - type: web
    name: my-web-app
    env: node
    buildCommand: npm install -g @redocly/cli
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: '3000'
