services:
  - type: web
    name: my-web-app
    env: node
    buildCommand: npm install -g @redocly/cli
    startCommand: node server.js
    envVars:
      - name: NODE_ENV
        value: production
      - name: PORT
        value: 3000
